name: Go Build Check
on:
  push:

env:
  TEST_TAG: ${{ github.event.repository.name }}/trash-level:test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Prep modules
      run: |
        go mod init example.com/trash-levels
        go mod tidy
    - name: Build
      run: go build -v main.go

  containerize:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and export Docker
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        load: true
        tags: ${{ env.TEST_TAG }}
    - name: Test
      run: |
        docker image ls
